### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by nextwebb**
Fixed readme markdown errors, associated with consuming the registrations API,
also fixed errors with User model , data cleanUp method.

### CODE REVIEW

**Review by Ebugo — COMMENTED** [review]
Why did you change this to typeof string? Numbers can also parse as string when sent in with alphabets remember?
Is there a problem with the isAlpha validations? I think it's best we use a particular library /method for validations

**Comment by nextwebb** [comment]
yea there was a problem with alpha validation, it prompted an error when ever there was spaces between words .for example it didn't read ` "state": "los angeles " and "city":"mount view" ` as an alpha string.

well it is true that numbers are also json strings :(

**Comment by Ebugo** [comment]
> yea there was a problem with alpha validation, it prompted an error when ever there was spaces between words .for example it didn't read `"state": "los angeles " and "city":"mount view"` as an alpha string.
> 
> well it is true that numbers are also json strings :(

Okay, I understand. We'd have to find a better solution later on.

**Comment by Ebugo** [comment]
There are conflicts in the Readme file.

**Review by Ebugo — APPROVED** [review]

**Pull request merged**
